name: Testing on PR for immediate feedback
run-name: Running tests, triggered by ${{ github.actor }}

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - 'dev'
env:
  REGISTRY: ghcr.io

jobs:
  CheckFormatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install Ruff
        run: pip install ruff
      - name: Check formatting with Ruff
        run: ruff check --output-format=github .
  Tests:
    runs-on: ubuntu-latest
    needs: [CheckFormatting]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install testing related requirements
        run: |
          pip install -r ./images/base/requirements.txt
          pip install pytest pytest-cov
      - name: Run Pytest
        run: pytest --cov=. --cov-report=term