name: Python Testing
run-name: Running tests, triggered by ${{ github.actor }}

on:
  pull_request:
    branches:
      - 'dev'
env:
  REGISTRY: ghcr.io

jobs:
  DockerBuildPush:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Tests:
    runs-on: ubuntu-latest
    needs: [DockerBuildPush]
    container:
      image: ghcr.io/${{ github.repository }}/:${{ needs.DockerBuildPush.outputs.labels }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Install base app requirements
          pip install -r ./test/requirements.txt
          # Install testing related requirements
          pip install pytest pytest-cov
      - run: pytest --cov=. --cov-report=term
      - name: Check formatting with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .